'use client';

import { useEffect } from 'react';
import type mapboxgl from 'mapbox-gl';
import { useMapStore } from '@/stores/map';
import { useAvyForecast } from '@/hooks/useAvyForecast';
import { AspectElevationRose, parseLocations } from '@/components/tour/AvyDangerBanner';

/**
 * True slope angle overlay using server-computed tiles.
 *
 * Each tile is generated by /api/slope-tile which decodes Mapbox Terrain-RGB
 * DEM data, computes slope via Horn's method, and returns a color-coded PNG.
 * The result is view-independent — camera pitch/bearing has no effect.
 *
 * Color scheme (CalTopo/avalanche standard):
 *   < 25°  = transparent (low angle)
 *   25-29° = green  (mellow)
 *   30-34° = yellow (moderate)
 *   35-39° = orange (prime avalanche zone)
 *   40-44° = red    (steep avalanche terrain)
 *   45-49° = dark red/pink (very steep)
 *   50°+   = purple (extreme cliffs)
 */

const SOURCE_ID = 'slope-angle-tiles';
const LAYER_ID = 'slope-angle-layer';

function removeAll(map: mapboxgl.Map) {
  try {
    if (map.getLayer(LAYER_ID)) map.removeLayer(LAYER_ID);
    if (map.getSource(SOURCE_ID)) map.removeSource(SOURCE_ID);
  } catch {
    // map may be torn down
  }
}

export function SlopeOverlay({ map }: { map: mapboxgl.Map | null }) {
  const showSlopeAngle = useMapStore((s) => s.showSlopeAngle);
  const { data: avyData } = useAvyForecast();

  useEffect(() => {
    if (!map) return;

    function apply() {
      if (!map!.isStyleLoaded()) return;

      if (!showSlopeAngle) {
        removeAll(map!);
        return;
      }

      if (!map!.getSource(SOURCE_ID)) {
        map!.addSource(SOURCE_ID, {
          type: 'raster',
          tiles: ['/api/slope-tile?z={z}&x={x}&y={y}'],
          tileSize: 256,
          maxzoom: 15,
        });
      }

      // Insert below route lines, markers, and other overlays
      const beforeLayer =
        map!.getLayer('selected-tour-route-casing') ? 'selected-tour-route-casing'
        : map!.getLayer('tour-markers-layer') ? 'tour-markers-layer'
        : undefined;

      if (!map!.getLayer(LAYER_ID)) {
        map!.addLayer(
          {
            id: LAYER_ID,
            type: 'raster',
            source: SOURCE_ID,
            paint: {
              'raster-opacity': 0.55,
            },
          },
          beforeLayer,
        );
      }
    }

    if (map.isStyleLoaded()) {
      apply();
    } else {
      map.once('styledata', apply);
    }

    return () => {
      map.off('styledata', apply);
      removeAll(map);
    };
  }, [map, showSlopeAngle]);

  if (!showSlopeAngle) return null;

  // Legend
  const ranges = [
    { label: '25-29°', color: '#4CAF50' },
    { label: '30-34°', color: '#FFEB3B' },
    { label: '35-39°', color: '#FF9800' },
    { label: '40-44°', color: '#F44336' },
    { label: '45-49°', color: '#E91E63' },
    { label: '50°+', color: '#9C27B0' },
  ];

  const problems = avyData?.detailed?.problems ?? [];

  return (
    <div className="rounded-lg bg-gray-900/85 px-3 py-2.5 text-xs text-white shadow-lg backdrop-blur-sm">
      <div className="mb-1.5 text-[10px] font-medium uppercase tracking-wider text-gray-300">
        Slope Angle
      </div>
      <div className="flex gap-0.5">
        {ranges.map((r) => (
          <div key={r.label} className="flex flex-col items-center">
            <div
              className="h-3 w-6 rounded-sm"
              style={{ background: r.color, opacity: 0.85 }}
            />
            <span className="mt-0.5 text-[8px] text-gray-400">{r.label}</span>
          </div>
        ))}
      </div>

      {/* Avy problem roses — cross-reference slope angles with problem aspects/elevations */}
      {problems.length > 0 && (
        <div className="mt-2 border-t border-white/20 pt-2">
          <div className="mb-1 text-[10px] font-medium uppercase tracking-wider text-gray-300">
            Avy Problem Aspects
          </div>
          <div className="space-y-2">
            {problems.map((p, i) => {
              const locations = parseLocations(p.location);
              return (
                <div key={i} className="flex items-center gap-2">
                  <AspectElevationRose locations={locations} />
                  <div className="flex-1">
                    <p className="text-[10px] font-medium text-white">{p.name}</p>
                    <p className="text-[9px] text-gray-400">
                      {p.likelihood} &middot; D{p.size[0]}–D{p.size[1]}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      <div className="mt-1.5 border-t border-white/20 pt-1 text-[9px] text-gray-500">
        &lt; 25° not shaded
      </div>
    </div>
  );
}
