'use client';

import { useEffect } from 'react';
import type mapboxgl from 'mapbox-gl';
import { useMapStore } from '@/stores/map';
import { isStyleReady } from '@/lib/mapStyle';

/**
 * True slope angle overlay using server-computed tiles.
 *
 * Each tile is generated by /api/slope-tile which decodes Mapbox Terrain-RGB
 * DEM data, computes slope via Horn's method, and returns a color-coded PNG.
 * The result is view-independent — camera pitch/bearing has no effect.
 *
 * Color scheme (CalTopo/avalanche standard):
 *   < 25°  = transparent (low angle)
 *   25-29° = green  (mellow)
 *   30-34° = yellow (moderate)
 *   35-39° = orange (prime avalanche zone)
 *   40-44° = red    (steep avalanche terrain)
 *   45-49° = dark red/pink (very steep)
 *   50°+   = purple (extreme cliffs)
 */

const SOURCE_ID = 'slope-angle-tiles';
const LAYER_ID = 'slope-angle-layer';

function removeAll(map: mapboxgl.Map) {
  try {
    if (map.getLayer(LAYER_ID)) map.removeLayer(LAYER_ID);
    if (map.getSource(SOURCE_ID)) map.removeSource(SOURCE_ID);
  } catch {
    // map may be torn down
  }
}

export function SlopeOverlay({ map }: { map: mapboxgl.Map | null }) {
  const showSlopeAngle = useMapStore((s) => s.showSlopeAngle);

  useEffect(() => {
    if (!map) return;

    function apply() {
      if (!isStyleReady(map!)) return;

      if (!showSlopeAngle) {
        removeAll(map!);
        return;
      }

      if (!map!.getSource(SOURCE_ID)) {
        map!.addSource(SOURCE_ID, {
          type: 'raster',
          tiles: ['/api/slope-tile?z={z}&x={x}&y={y}'],
          tileSize: 256,
          maxzoom: 15,
        });
      }

      // Insert below route lines, markers, and other overlays
      const beforeLayer =
        map!.getLayer('selected-tour-route-casing') ? 'selected-tour-route-casing'
        : map!.getLayer('tour-markers-layer') ? 'tour-markers-layer'
        : undefined;

      if (!map!.getLayer(LAYER_ID)) {
        map!.addLayer(
          {
            id: LAYER_ID,
            type: 'raster',
            source: SOURCE_ID,
            paint: {
              'raster-opacity': 0.55,
            },
          },
          beforeLayer,
        );
      }
    }

    let retryTimer: ReturnType<typeof setTimeout> | null = null;
    let cancelled = false;
    function tryApply() {
      if (cancelled) return;
      if (isStyleReady(map!)) { apply(); } else { retryTimer = setTimeout(tryApply, 50); }
    }
    tryApply();

    return () => {
      cancelled = true;
      if (retryTimer) clearTimeout(retryTimer);
      removeAll(map);
    };
  }, [map, showSlopeAngle]);

  return null;
}
